config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations'  }

  root to: 'home#index'
  get 'description', to: 'home#description'

  #nested resources
  resources :users do
    resources :articles
  end

  resources :articles, :journals
  resources :searches
  resources :demands

  get 'present_user', to: 'users#present_user'
  #get '/users/:id', to: 'authors#show'
  # get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, presence: true

  has_many :article_users
  has_many :articles, :through => :article_users

  has_many :active_requests, class_name: 'Demand',
                             foreign_key: 'reader_id',
                             dependent: :destroy
  has_many :passive_requests, class_name: 'Demand',
                              foreign_key: 'author_id',
                              dependent: :destroy
  has_many :authors, :through => :active_requests
  has_many :readers, :through => :passive_requests


  def self.from_omniauth(access_token)
     data = access_token.info
     user = User.where(:email => data["email"]).first

     unless user
         user = User.create(
            email: data[:email],
            first_name: data[:first_name],
            last_name: data[:last_name],
            password: Devise.friendly_token[0,20]
         )
     end
     user
   end

   def self.search(first_name, last_name)
     User.where("first_name = ? AND last_name = ?" , first_name, last_name)
   end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = []
    @users = User.search(params[:first_name], params[:last_name])
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user }
    end
  end

  def present_user
    render json: {id: current_user.id }
  end

end

app/views/users/index.html.erb
<h4>Find Article by Author Name</h4>
<%= form_tag users_path, :method => 'get' do %>
  <p>
    First Name: <%= text_field_tag :first_name %>
    Last Name: <%= text_field_tag :last_name %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<br></br>
<% if @users.any? %>
  <% @users.each do |user| %>
    <h5>
      Please click the author's name below to see the author's articles:
      <br></br>
      <%= link_to "#{user.first_name} #{user.last_name}", user_articles_path(user) %>
    </h5>
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>
  Welcome <%= current_user.first_name %> <%= current_user.last_name %>
</p>
<br>
<h4>Edit Your Profile or Cancel Your Account</h4>
<ul>
  <li><%= link_to "Edit or Cancel", edit_user_registration_path %></li>
</ul>
<br>

<h4>Add Your Article</h5>
  <ul>
    <li><%= link_to "Add your Article", new_user_article_path(current_user) %></li>
  </ul>
<br>

<h4> Your Posted Articles </h4>
<ul>
  <li><%= link_to "Your Articles", user_articles_path(current_user) %></li>
</ul>