config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations'  }

  root to: 'home#index'
  get 'description', to: 'home#description'

  #nested resources
  resources :users do
    resources :articles
  end

  resources :articles, :journals
  resources :searches
  resources :demands

  get 'present_user', to: 'users#present_user'
  #get '/users/:id', to: 'authors#show'
  # get '/auth/:provider/callback', to: 'sessions#create'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def description
  end

  def author_search
  end

end

app/views/home/description.html.erb
<h4>How it works:</h4>
<ul>
  <li>Authors post information on their scientific literatures.</li>
  <li>Readers search scientific literatures by doi(Digital object identifier).</li>
  <li>Readers, after finding the literature they want to read, request it from the author of the literature.</li>
  <li>Author sends the literature to Reader via email.</li>
</ul>

app/views/home/index.html.erb
<h2>Scientific Article Sharing Website! </h2>
<h4><i>Scientific Literatures Shared by Authors</i></h4>
<br>

<% if current_user && current_user.passive_requests.any? %>
  <h4> Request from other users </h4>
  <ul>
  <% current_user.passive_requests.each do |req| %>
    <li>
      <%= User.find(req.reader_id).first_name %>
      requested "<%= link_to Article.find(req.article_id).title, demand_path(req) %>"
    </li>
  <% end %>
  </ul>
<% end %>
<br>

<h4> Post your article </h4>

<h5>If you are an author of scientific literatures and would like to share yours with others, please list your literatures here!</h5>
<% if user_signed_in? %>
  <%= link_to "Post your Article", new_user_article_path(current_user) %>
<% end %>
<br>
</br>

<h4>Search</h4>
<p> type DOI (Digital Object Identifier) of the literature you are looking for: </P>
<% if user_signed_in? %>
  <%= form_tag searches_path, :method => 'post' do %>
    <p>
      <%= text_field_tag :doi %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
<% else %>
  <br>
  <font color="green">
      Please
      <%= link_to "Sign up", new_user_registration_path %>
      or
      <%= link_to "Sign in", new_user_session_path %>
      to List or Search Articles
    </font>
<% end %>