config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations'  }

  root to: 'home#index'
  get 'description', to: 'home#description'

  #nested resources
  resources :users do
    resources :articles
  end

  resources :articles, :journals
  resources :searches
  resources :demands

  get 'present_user', to: 'users#present_user'
  #get '/users/:id', to: 'authors#show'
  # get '/auth/:provider/callback', to: 'sessions#create'
end

app/views/layouts/_header.html.erb
<header>

    <nav>
      <div class="_row clearfix">
        <%= image_tag("hanlee_logo.png", alt: "hanlee logo") %>
        <ul class="main-nav">
            <% if user_signed_in? %>
            <li role="presentation"> <%= link_to "Welcome #{current_user.first_name}", user_path(current_user)  %></li>
            <% end %>
            <li> <%= link_to "Home", root_path %> </li>
            <li> <%= link_to "How it works", description_path %> </li>
            <% if user_signed_in? %>
              <li role="presentation"> <%= link_to "Articles", articles_path %></li>
              <li role="presentation"> <%= link_to "Author Search", users_path %></li>
              <li role="presentation"> <%= link_to "Sign out", destroy_user_session_path, :method => :delete%></li>
            <% else %>
              <li role="presentation"> <%= link_to "Sign in", new_user_session_path %></li>
              <li role="presentation"> <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %></li>
              <li role="presentation" > <%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
        </ul>
      </div>
    </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalShare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  </head>

  <body>
    <%= render 'layouts/header' %>
    <section>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="container">
        <%= yield %>
      </div>
    </section>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>